version: '3.7'
services:
  zookeeper-container:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka-broker-container:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-container
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-container:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-container:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafdrop-container:
        image: obsidiandynamics/kafdrop
        container_name: kafdrop-container
        platform: linux/amd64
        ports:
          - "9001:9000"
        networks:
          - sfd-microservice-example-network
        environment:
          KAFKA_BROKERCONNECT: kafka-broker-container:9092,localhost:29092
        depends_on:
          - kafka-broker-container
          - zookeeper-container
networks:
  sfd-microservice-example-network:
    driver: bridge
volumes:
 mongodb_data_container: {}