server:
  port: 8085
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      instance:
        appname: kafka-manager
instance:
  preferIpAddress: true

spring:
  application:
    name: kafka-manager
  kafka:
    bootstrap-servers: localhost:29092,localhost:9092
    admin:
      auto-create: true
      fail-fast: true
      close-timeout: 1

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health","prometheus", "metrics" ]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true