server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      instance:
        appname: authentication-service
instance:
  preferIpAddress: true
spring:
  application:
    name: authentication-service
  data:
    mongodb:
      database: authentication-mongo-db
      host: localhost
      port: 27017
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health","prometheus", "metrics" ]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true