server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      instance:
        appname: order-service
instance:
  preferIpAddress: true
spring:
  application:
    name: order-service
  kafka:
    bootstrap-servers: localhost:29092,localhost:9092
    admin:
      auto-create: true
      fail-fast: true
      close-timeout: 1
  data:
    mongodb:
      database: order-mongo-db
      host: localhost
      port: 27017

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health","prometheus", "metrics" ]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true