eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server-container:8761/eureka/
spring:
  kafka:
    bootstrap-servers: kafka-broker-container:9092,localhost:29092
    admin:
      auto-create: true
      fail-fast: true
      close-timeout: 1
  data:
    mongodb:
      database: inventory-mongo-db
      username: root
      password: mongopw
      host: mongodb-container
      port: 27017