eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server-container:8761/eureka/
spring:
  data:
    mongodb:
      database: inventory-mongo-db
      username: root
      password: mongopw
      host: mongodb-container
      port: 27017